Vagrant.configure("2") do |config|
   
  config.vm.define "swarmmaster" do | swarmmaster |
    swarmmaster.vm.box = "centos/7"
    swarmmaster.vm.network "public_network", ip: "192.168.0.100" 
    swarmmaster.vm.provision :docker
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "centos/7"
    node1.vm.network "public_network", ip: "192.168.0.101" 
    node1.vm.provision :docker
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "centos/7"
    node2.vm.network "public_network", ip: "192.168.0.102" 
    node2.vm.provision :docker
  end

end
