Vagrant.configure("2") do |config|
   
  config.vm.define "jenkins_git" do | jenkins_git |
    jenkins_git.vm.box = "centos/7"
    jenkins_git.vm.provision :shell , path: "provision.sh"
    jenkins_git.vm.network "public_network", ip: "192.168.0.200" 
  end

end
