Vagrant.configure("2") do |config|
   
  config.vm.define "k8smaster" do | k8smaster |
    k8smaster.vm.box = "centos/7"
    k8smaster.vm.network "public_network", ip: "192.168.0.100" 
    k8smaster.vm.provision :shell , path: "provision.sh"
  end

  config.vm.provider :virtualbox do | k8smaster |
    k8smaster.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "centos/7"
    node1.vm.network "public_network", ip: "192.168.0.101" 
    node1.vm.provision :shell , path: "provision.sh"

  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "centos/7"
    node2.vm.network "public_network", ip: "192.168.0.102" 
    node2.vm.provision :shell , path: "provision.sh"
  end

end
